import java.io.Serializable;

/**
 * コンテンツ詳細 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RecordContentDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** レコード情報. */
	private RecordContentInf recordContentInf;

	/** 詳細ID. */
	private Integer detailId;

	/** 固定項目情報. */
	private FixedItemInf fixedItemInf;

	/** 項目名. */
	private String indexName;

	/** 内容. */
	private String mainText;

	/**
	 * コンストラクタ.
	 */
	public RecordContentDetail() {
	}

	/**
	 * id を設定します.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * id を取得します.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * レコード情報 を設定します.
	 * 
	 * @param recordContentInf
	 *            レコード情報
	 */
	public void setRecordContentInf(RecordContentInf recordContentInf) {
		this.recordContentInf = recordContentInf;
	}

	/**
	 * レコード情報 を取得します.
	 * 
	 * @return レコード情報
	 */
	public RecordContentInf getRecordContentInf() {
		return this.recordContentInf;
	}

	/**
	 * 詳細ID を設定します.
	 * 
	 * @param detailId
	 *            詳細ID
	 */
	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	/**
	 * 詳細ID を取得します.
	 * 
	 * @return 詳細ID
	 */
	public Integer getDetailId() {
		return this.detailId;
	}

	/**
	 * 固定項目情報 を設定します.
	 * 
	 * @param fixedItemInf
	 *            固定項目情報
	 */
	public void setFixedItemInf(FixedItemInf fixedItemInf) {
		this.fixedItemInf = fixedItemInf;
	}

	/**
	 * 固定項目情報 を取得します.
	 * 
	 * @return 固定項目情報
	 */
	public FixedItemInf getFixedItemInf() {
		return this.fixedItemInf;
	}

	/**
	 * 項目名 を設定します.
	 * 
	 * @param indexName
	 *            項目名
	 */
	public void setIndexName(String indexName) {
		this.indexName = indexName;
	}

	/**
	 * 項目名 を取得します.
	 * 
	 * @return 項目名
	 */
	public String getIndexName() {
		return this.indexName;
	}

	/**
	 * 内容 を設定します.
	 * 
	 * @param mainText
	 *            内容
	 */
	public void setMainText(String mainText) {
		this.mainText = mainText;
	}

	/**
	 * 内容 を取得します.
	 * 
	 * @return 内容
	 */
	public String getMainText() {
		return this.mainText;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RecordContentDetail other = (RecordContentDetail) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
