package dailyReport.resource;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * campany_detail モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@NamedQueries({
	@NamedQuery(
			name="campanyDetailAll",
			query="SELECT c FROM CampanyDetail c")
})
@Table(name="campany_detail")
public class CampanyDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** campany_id. */
	@Id
	@Column(name="campany_id")
	private Integer campany_id;

	/** campanyタイトル. */
	@Column(name="campany_title")
	private String campany_title;

	/**
	 * コンストラクタ.
	 */
	public CampanyDetail() {
	}

	/**
	 * campany_id を設定します.
	 * 
	 * @param campany_id
	 *            campany_id
	 */
	public void setCampanyId(Integer campany_id) {
		this.campany_id = campany_id;
	}

	/**
	 * campany_id を取得します.
	 * 
	 * @return campany_id
	 */
	public Integer getCampanyId() {
		return this.campany_id;
	}

	/**
	 * campanyタイトル を設定します.
	 * 
	 * @param campany_title
	 *            campanyタイトル
	 */
	public void setCampanyTitle(String campany_title) {
		this.campany_title = campany_title;
	}

	/**
	 * campanyタイトル を取得します.
	 * 
	 * @return campanyタイトル
	 */
	public String getCampanyTitle() {
		return this.campany_title;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((campany_id == null) ? 0 : campany_id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CampanyDetail other = (CampanyDetail) obj;
		if (campany_id == null) {
			if (other.campany_id != null) {
				return false;
			}
		} else if (!campany_id.equals(other.campany_id)) {
			return false;
		}
		return true;
	}

}
