package dailyReport.resource;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * family_i情報 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@NamedQueries({
	@NamedQuery(
			name="searchUserFamily",
			query="SELECT f FROM FamilyInf f WHERE f.user_id = :user_id"),
	@NamedQuery(
			name="deleteUserFamily",
			query="DELETE FROM FamilyInf f WHERE f.user_id = :user_id")
})
@Table(name="family_inf")
public class FamilyInf implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@Column(name="id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	/** ユーザid. */
	@Column(name="user_id")
	private String user_id;

	/** family名. */
	@Column(name="family_name")
	private String family_name;

	/** family名カナ. */
	@Column(name="family_name_kana")
	private String family_name_kana;

	/** family関連ation. */
	@Column(name="family_relation")
	private String family_relation;

	/** family_support. */
	@Column(name="family_support")
	private Integer family_support;

	/**
	 * コンストラクタ.
	 */
	public FamilyInf() {
	}

	/**
	 * id を設定します.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * id を取得します.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * ユーザid を設定します.
	 * 
	 * @param user_id
	 *            ユーザid
	 */
	public void setUserId(String user_id) {
		this.user_id = user_id;
	}

	/**
	 * ユーザid を取得します.
	 * 
	 * @return ユーザid
	 */
	public String getUserId() {
		return this.user_id;
	}

	/**
	 * family名 を設定します.
	 * 
	 * @param family_name
	 *            family名
	 */
	public void setFamilyName(String family_name) {
		this.family_name = family_name;
	}

	/**
	 * family名 を取得します.
	 * 
	 * @return family名
	 */
	public String getFamilyName() {
		return this.family_name;
	}

	/**
	 * family名カナ を設定します.
	 * 
	 * @param family_name_kana
	 *            family名カナ
	 */
	public void setFamilyNameKana(String family_name_kana) {
		this.family_name_kana = family_name_kana;
	}

	/**
	 * family名カナ を取得します.
	 * 
	 * @return family名カナ
	 */
	public String getFamilyNameKana() {
		return this.family_name_kana;
	}

	/**
	 * family関連ation を設定します.
	 * 
	 * @param family_relation
	 *            family関連ation
	 */
	public void setFamilyRelation(String family_relation) {
		this.family_relation = family_relation;
	}

	/**
	 * family関連ation を取得します.
	 * 
	 * @return family関連ation
	 */
	public String getFamilyRelation() {
		return this.family_relation;
	}

	/**
	 * family_support を設定します.
	 * 
	 * @param family_support
	 *            family_support
	 */
	public void setFamilySupport(Integer family_support) {
		this.family_support = family_support;
	}

	/**
	 * family_support を取得します.
	 * 
	 * @return family_support
	 */
	public Integer getFamilySupport() {
		return this.family_support;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FamilyInf other = (FamilyInf) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
