package dailyReport.resource;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * position_detail モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@NamedQueries({
	@NamedQuery(
			name="positionDetailAll",
			query="SELECT p FROM PositionDetail p")
})
@Table(name="position_detail")
public class PositionDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** position_id. */
	@Id
	@Column(name="position_id")
	private Integer position_id;

	/** positionタイトル. */
	@Column(name="position_title")
	private String position_title;

	/**
	 * コンストラクタ.
	 */
	public PositionDetail() {
	}

	/**
	 * position_id を設定します.
	 * 
	 * @param position_id
	 *            position_id
	 */
	public void setPositionId(Integer position_id) {
		this.position_id = position_id;
	}

	/**
	 * position_id を取得します.
	 * 
	 * @return position_id
	 */
	public Integer getPositionId() {
		return this.position_id;
	}

	/**
	 * positionタイトル を設定します.
	 * 
	 * @param position_title
	 *            positionタイトル
	 */
	public void setPositionTitle(String position_title) {
		this.position_title = position_title;
	}

	/**
	 * positionタイトル を取得します.
	 * 
	 * @return positionタイトル
	 */
	public String getPositionTitle() {
		return this.position_title;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((position_id == null) ? 0 : position_id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PositionDetail other = (PositionDetail) obj;
		if (position_id == null) {
			if (other.position_id != null) {
				return false;
			}
		} else if (!position_id.equals(other.position_id)) {
			return false;
		}
		return true;
	}

}
