package dailyReport.resource;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * qualification_detail モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="qualification_detail")
public class QualificationDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** qualification_id. */
	@Id
	@Column(name="qualification_id")
	private Integer qualification_id;

	/** qualificationタイトル. */
	@Column(name="qualification_title")
	private String qualification_title;

	/**
	 * コンストラクタ.
	 */
	public QualificationDetail() {
	}

	/**
	 * qualification_id を設定します.
	 * 
	 * @param qualification_id
	 *            qualification_id
	 */
	public void setQualificationId(Integer qualification_id) {
		this.qualification_id = qualification_id;
	}

	/**
	 * qualification_id を取得します.
	 * 
	 * @return qualification_id
	 */
	public Integer getQualificationId() {
		return this.qualification_id;
	}

	/**
	 * qualificationタイトル を設定します.
	 * 
	 * @param qualification_title
	 *            qualificationタイトル
	 */
	public void setQualificationTitle(String qualification_title) {
		this.qualification_title = qualification_title;
	}

	/**
	 * qualificationタイトル を取得します.
	 * 
	 * @return qualificationタイトル
	 */
	public String getQualificationTitle() {
		return this.qualification_title;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((qualification_id == null) ? 0 : qualification_id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		QualificationDetail other = (QualificationDetail) obj;
		if (qualification_id == null) {
			if (other.qualification_id != null) {
				return false;
			}
		} else if (!qualification_id.equals(other.qualification_id)) {
			return false;
		}
		return true;
	}

}
