package dailyReport.resource;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * qualification_i情報 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@NamedQueries({
	@NamedQuery(
			name="searchUserQualification",
			query="SELECT q FROM QualificationInf q WHERE q.user_id = :user_id")
})
@Table(name="qualification_inf")
public class QualificationInf implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@Column(name="id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	/** ユーザid. */
	@Column(name="user_id")
	private String user_id;

	/** qualification_id. */
	@Column(name="qualification_id")
	private Integer qualification_id;

	/**
	 * コンストラクタ.
	 */
	public QualificationInf() {
	}

	/**
	 * id を設定します.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * id を取得します.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * ユーザid を設定します.
	 * 
	 * @param user_id
	 *            ユーザid
	 */
	public void setUserId(String user_id) {
		this.user_id = user_id;
	}

	/**
	 * ユーザid を取得します.
	 * 
	 * @return ユーザid
	 */
	public String getUserId() {
		return this.user_id;
	}

	/**
	 * qualification_id を設定します.
	 * 
	 * @param qualification_id
	 *            qualification_id
	 */
	public void setQualificationId(Integer qualification_id) {
		this.qualification_id = qualification_id;
	}

	/**
	 * qualification_id を取得します.
	 * 
	 * @return qualification_id
	 */
	public Integer getQualificationId() {
		return this.qualification_id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		QualificationInf other = (QualificationInf) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
