package dailyReport.resource;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * tel_i情報 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@NamedQueries({
	@NamedQuery(
			name="searchUserTel",
			query="SELECT t FROM TelInf t WHERE t.user_id = :user_id"),
	@NamedQuery(
			name="deleteUserTel",
			query="DELETE FROM TelInf t WHERE t.user_id = :user_id")
})
@Table(name="tel_inf")
public class TelInf implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@Column(name="id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	/** ユーザid. */
	@Column(name="user_id")
	private String user_id;

	/** telタイトル. */
	@Column(name="tel_title")
	private String tel_title;

	/** tel. */
	@Column(name="tel")
	private String tel;

	/**
	 * コンストラクタ.
	 */
	public TelInf() {
	}

	/**
	 * id を設定します.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * id を取得します.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * ユーザid を設定します.
	 * 
	 * @param user_id
	 *            ユーザid
	 */
	public void setUserId(String user_id) {
		this.user_id = user_id;
	}

	/**
	 * ユーザid を取得します.
	 * 
	 * @return ユーザid
	 */
	public String getUserId() {
		return this.user_id;
	}

	/**
	 * telタイトル を設定します.
	 * 
	 * @param tel_title
	 *            telタイトル
	 */
	public void setTelTitle(String tel_title) {
		this.tel_title = tel_title;
	}

	/**
	 * telタイトル を取得します.
	 * 
	 * @return telタイトル
	 */
	public String getTelTitle() {
		return this.tel_title;
	}

	/**
	 * tel を設定します.
	 * 
	 * @param tel
	 *            tel
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * tel を取得します.
	 * 
	 * @return tel
	 */
	public String getTel() {
		return this.tel;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TelInf other = (TelInf) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
